name: deploy

on:
  push:
    branches: main

jobs:
  download: 
    runs-on: [self-hosted, linux, x64]  
    steps:  
    - name: download new changes
      uses: actions/checkout@v2
  move_files:
    runs-on: [self-hosted, linux, x64]
    needs: download
    steps:
    - name: remove previous data
      run: sudo rm -rf /var/www/html/*
    - name: copy files to apache
      run: sudo cp -R web/* /var/www/html/