name: deploy

on:
  push:
    branches: main

jobs:
  download: 
    runs-on: [self-hosted, linux, x64]  
    steps:  
    - name: download new changes
      uses: actions/checkout@v2
  build:
    runs-on: [self-hosted, linux, x64]  
    needs: download
    steps:  
    - name: install dependencies
      run: npm install
      working-directory: ipo-visusal
  restart:
    runs-on: [self-hosted, linux, x64]
    needs: build
    steps:
    - name: restart
      run: sudo pm2 restart pm2.json
    - name: save process status
      run: sudo pm2 save